$(document).ready(function()
{
    $('header').load("include/cabecalho.html");
    $('footer').load("include/footer.html");
    $('#sobre').load("include/sobre.html");
    $('#historia').load("include/historia.html");
    $('#novidades').load("include/novidades.html");
    $('#mais_vendidos').load("include/mais_vendidos.html");
    $('#diferenciais').load("include/diferenciais.html");
});